// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://itescalcmmhhlzsmgdfv.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0ZXNjYWxjbW1oaGx6c21nZGZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIxMTgwMTIsImV4cCI6MjA4NzY5NDAxMn0.8Mi6u5wI9jbRIyxubba13JdTj8qCd2u48vLdA1SFSho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Cliente sem tipagem para tabelas não presentes nos tipos gerados (campanhas, tabela_campanha, etc.)
export const supabaseUntyped = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
